### ISSUE TITLE
Add my website

### ISSUE THREAD

**Issue by alfianuinws** [108kb/w3#1]
https://alfianguide.blogspot.com/

**Comment by 108kb** [comment]
Hi, thanks.

Do you have your own domain? I mean, a domain that you can control? Since alfianguide.blogspot.com is rely on blogspot.com, I can't guarantee for it 😀✌️

**Comment by alfianuinws** [comment]
Is it only need domain or the hosting also? If only domain, how about https://www.ulumulislamiyah.com? I control it, but... you know, it based on blogger also.
